spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/data-jpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  logging.level:
    org.hibernate.SQL: debug
    # org.hibernate.type :trace  # 파라미터 바인딩된 부분까지 나온다.